import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'


export default function Home() {
  const [state, setState] = useState({a: 0, method: '+', b: 0, result: 0})

  const handleAChange = (e) => {
    handleResultChange(e.target.value, state.b, state.method)
  }

  const handleBChange = (e) => {
    handleResultChange(state.a, e.target.value, state.method)
  }

  const handleMethodChange = (e) => {
    handleResultChange(state.a, state.b, e.target.value)
  }

  const handleResultChange = (a, b, method) => {
    let result;
    switch(method){
      case '+':
        result = parseInt(a) + parseInt(b);
        break
      case '-':
        result = parseInt(a) - parseInt(b);
        break
      case '*':
        result = parseInt(a) * parseInt(b);
        break
      case '/':
        result = parseInt(a) / parseInt(b);
       break
      default:
        result = 0
        break
    }
    setState({...state, a: a, method: method, b: b, result: result})
  }

  const handleClick = () => {
    let result = state.result
    document.getElementById('a').value = result;
    document.getElementById('b').value = 0;
    document.getElementById('method').value = "+";
    document.getElementById('result').value = 0;
    setState({...state, a: result, method: '+', b: 0, result: 0})

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Quadro Negro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Square+Peg&display=swap" rel="stylesheet" />
      </Head>
      <h1 className={styles.title}>Aula de Matemática</h1>
      <main className={styles.main}>

        <select id="method" onChange={handleMethodChange} className="relative -left-20 top-12 bg-transparent">
          <option value="+">+</option>
          <option value="-">-</option>
          <option value="*">x</option>
          <option value="/">÷</option>
        </select>
        <div className="grid grid-row-3">
          <input className="text-right bg-transparent" id="a" type="number" placeholder='quanto' onChange={(handleAChange)}></input>
          <input className="text-right bg-transparent" id="b" type="number" placeholder='por quanto' onChange={(handleBChange)}></input>
          <h1  id="result" type="number" placeholder='dá' className="border-t-2 pr-4 text-right">{state.result}</h1>
        </div>
        <button className="relative -right-16 bottom-5" onClick={()=>{handleClick()}}>✔️</button>

      </main>

      <footer className={styles.footer}>
        <a>Um projeto @Primata</a>
      </footer>
    </div>
  )
}
